--- # https://poggit.pmmp.io/ci/robske110/SignServerStats
branches:
- master
projects:
  SSS:
    path: SSS/
  StatusList:
    path: examples/StatusList/
  WarnOffline:
    path: examples/WarnOffline/
...